###               ____                    _
#  ____ _____  __/ ___\_   _  __ _ _ ____| |
# / __// _ \ \/ / /  _| | | |/ _' | '_/ _' |
# \__ \  __/>  <\ \_| | |_| | (_) | || (_) |
# /___/\___/_/\_\\____/\___/ \__,_|_| \__,_|
#
#          MAIN CONFIGURATION FILE
###
# АВТОР:   sex_KAMAZ
# КОНТАКТ: vk.com/infernopage
#          t.me/sex_kamaz
# ПОМОЩЬ:  t.me/joinchat/EbZB3BKGfsu0DdbDNmpPjg
###
# РАЗРЕШЕНИЯ:
#   sexguard.command.rg: доступ к основной команде.
#     по-умолчанию:      для всех игроков.
#
#   sexguard.noflag: возможность игнорировать флаги.
#     по-умолчанию:  для операторов.
#
#   sexguard.all:   полный доступ.
#     по-умолчанию: для операторов.
###
# ДОПОЛНИТЕЛЬНЫЕ ПЛАГИНЫ:
#   PurePerms:  контроль размера и количества
#               регионов для групп.
#   UniGroup:   альтернативный менеджер групп.
#   EconomyAPI: покупка и продажа регионов.
#   UniMoney:   альтернативная экономика.
###
# ОШИБКИ В РАБОТЕ ПЛАГИНА?
#   Убедитесь в том, что случайно
#   не удалили один из пунктов
#   настроек.
#   Для возвращения конфига в его
#   нормальное состояние просто
#   удалите его - он восстановится
#   при включении плагина.
###
sign: e1814edea3c42ed4f53e326f7a396d18


###
# СВЯЗЬ С PurePerms:
#   Разрешить плагину работать с менеджером разрешений
#   для определения размеров и количества регионов для
#   каждой (или отдельной) из его групп.
#   В противном случае будет использоваться
#   пункт default в group.yml для всех игроков.
#   Настроить группы можно в group.yml.
###
# РАЗРЕШИТЬ: true
# ЗАПРЕТИТЬ: false
allow_pureperms: false
###
# СВЯЗЬ С UniGroup:
#   Разрешить плагину работать с альтернативным
#   менеджером групп.
###
# РАЗРЕШИТЬ: true
# ЗАПРЕТИТЬ: false
allow_universalgroup: false


###
# СВЯЗЬ С EconomyAPI:
#   Разрешить плагину работать с экономикой
#   для возможности продажи регионов.
#   Актуально для roleplay и survival.
###
# РАЗРЕШИТЬ: true
# ЗАПРЕТИТЬ: false
allow_economyapi: false
###
# СВЯЗЬ С UniMoney:
#   Разрешить плагину работать с альтернативной
#   экономикой.
###
# РАЗРЕШИТЬ: true
# ЗАПРЕТИТЬ: false
allow_universalmoney: false
###
# ПРОДАЖА РЕГИОНА ЧЕРЕЗ ТАБЛИЧКУ:
# (требуется связь с экономикой)
#   Разрешить владельцам продавать
#   свои регионы через табличку.
#   Актуально для создания квартир.
###
# ФОРМА ОФОРМЛЕНИЯ ТАБЛИЧКИ:
#   1 строка: sell region
#   2 строка: <цена>
#   3 строка:
#   4 строка:
###
# АКТИВИРОВАТЬ: true
# ВЫКЛЮЧИТЬ:    false
allow_sell: false
###
# ПЛАТА ЗА СОЗДАНИЕ РЕГИОНА:
# (требуется связь с экономикой)
#   Установить обязательную плату для игроков
#   без полного доступа за создание нового региона
#   при помощи команды.
###
# РАЗРЕШИТЬ: true
# ЗАПРЕТИТЬ: false
pay_for_region: false
###
# ЦЕНА СОЗДАНИЯ НОВОГО РЕГИОНА:
# (требуется разрешить параметр платы за регион)
#   Установить цену за создание нового региона
#   игрокам без полного доступа.
price: 200


###
# БЕЗОПАСНЫЙ РЕЖИМ:
#   Запрещает игрокам без полного доступа
#   ставить и ломать блоки, пока они
#   находятся вне региона с разрешенным
#   на то флагом, либо вне своего региона.
#   Актуально для roleplay и minigames.
###
# АКТИВИРОВАТЬ: true
# ВЫКЛЮЧИТЬ:    false
safe_mode: false


###
# РЕЖИМ РЕГИОНОВ ВО ВСЮ ВЫСОТУ:
#   В этом режиме каждый новый регион
#   будет создаваться без учета высоты
#   (как чанк).
#   Не знаю, нахрена кому-либо нужна эта фича,
#   но создавать регионы с ней действительно
#   удобно.
# Обратите внимание, что в настройках размера
# регионов вместо их объема в блоках будет
# высчитываться площадь (без учета высоты).
###
# АКТИВИРОВАТЬ: true
# ВЫКЛЮЧИТЬ:    false
full_height: false


###
# ТИП ОПОВЕЩЕНИЯ:
#   Способ оповещения игроков при
#   запрете действий внутри регионов.
###
# POPUP:   0
# MESSAGE: 1
# TIP:     2
warn_type: 2


###
# ФЛАГИ:
#   Стандартные значения флагов
#   при создании нового региона.
###
# INTERACT: открывание жел. дверей, нажатие кнопок и т.п.
# TELEPORT: телепортация из региона.
# COMBUST:  возгорание существ.
# EXPLODE:  любые взрывы внутри региона.
# CHANGE:   изменение региона существами (падающий песок и т.п.).
# BUCKET:   использование ведер.
# DAMAGE:   получение урона от внешнего мира.
# CHEST:    доступ к сундукам.
# FRAME:    доступ к рамкам.
# PLACE:    возможность ставить блоки.
# BREAK:    возможность ломать блоки.
# SLEEP:    возможность ложиться в кровать.
# DECAY:    разрешить исчезать листве с деревьев.
# DROP:     возможность выбрасывать вещи.
# CHAT:     отправка сообщений в чат.
# PVP:      возможность наносить урон игрокам.
# MOB:      возможность наносить урон существам.
###
# Чтобы запретить игрокам использовать
# какой-либо флаг, просто удалите или
# закомментируйте его.
# Но только после того, как создадите
# нужные вам регионы (спавн, арена и т.д.)
# (поставьте # перед пунктом)
###
# ВКЛЮЧИТЬ:  true
# ВЫКЛЮЧИТЬ: false
allowed_flag:
  interact: true
  teleport: true
  combust: false
  explode: false
  change: false
  bucket: false
  damage: true
  chest: false
  frame: false
  place: false
  break: false
  sleep: false
  decay: true
  drop: true
  chat: true
  pvp: false
  mob: true